# deploy/docker-compose.yml

version: '3.8'

services:
  laravel:
    restart: unless-stopped
    container_name: laravelapp
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    # allocate as many volumes as necessary, if needed.
    volumes:
      - ../storage/app:/var/www/html/storage/app
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_VERSION: ${APP_VERSION}
      APP_URL: ${APP_URL}
      DB_CONNECTION : ${DB_CONNECTION}
      DB_HOST : ${DB_HOST}
      DB_PORT : 3306
      DB_DATABASE : ${DB_DATABASE}
      DB_USERNAME : ${DB_USERNAME}
      DB_PASSWORD : ${DB_PASSWORD}
      DB_PEGAWAI_CONNECTION : ${DB_PEGAWAI_CONNECTION}
      DB_PEGAWAI_HOST : ${DB_PEGAWAI_HOST}
      DB_PEGAWAI_PORT : 3306
      DB_PEGAWAI_DATABASE : ${DB_PEGAWAI_DATABASE}
      DB_PEGAWAI_USERNAME : ${DB_PEGAWAI_USERNAME}
      DB_PEGAWAI_PASSWORD : ${DB_PEGAWAI_PASSWORD}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    ports:
      - "8080:80"
    networks:
      - n-laravel
  #   depends_on:
  #     - database

  # database:
  #   restart: unless-stopped
  #   image: mariadb:lts-jammy
  #   volumes:
  #     - v-database:/var/lib/mysql
  #   environment:
  #     MARIADB_DATABASE: ${DB_DATABASE}
  #     MARIADB_USER: ${DB_USERNAME}
  #     MARIADB_PASSWORD: ${DB_PASSWORD}
  #     MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #   networks:
  #     - n-laravel

# volumes:
#   v-database:


networks:
  n-laravel:
    driver: bridge